### ISSUE TITLE
Actions on Device Screen doesn't get updated if state changes through external client action.

### ISSUE THREAD

**Issue by anil614sagar** [zettaios/zetta#11]
For example, if you use zetta browser to change the state then state gets changed in App but not Action which results in broken experience.

**Comment by benpackard** [comment]
I think this is related to the enhancement we discussed on our call. The stream gets a new signal from ZettaKit, but it only contains the new value for the updated property, not the full device state.

**Comment by landlessness** [comment]
The available actions for a device depend on its current state. If a light is in state `off` then the only available action would be `turn-on`. Once `turn-on` is pushed and the state changes to `on` then the only available action button should be `turn-off`.

Here is a scenario I am experiencing with a security system on the iOS app. The security system has three states: `disarmed`, `armed-stay` and `armed-away`. If the current state is `disarmed` then the available actions should be `arm-stay` and `arm-away`. If the current state is `armed-stay` or `armed-away` then the only available action should be `disarm`. Whenever an action is pressed and the state changes the available actions should change accordingly. 
- The first attached screenshot shows a starting state of `disarmed` and the two available actions of `arm-stay` and `arm-away`. 
- The second screenshot shows the app after `arm-away` was pressed. The current state correctly displays `armed-away`. However, the only available action should be `disarm` but instead we still see the original actions `arm-stay` and `arm-away`.

We will probably want to loop in @mdobson to design the best solution for this issue.

![img_1409](https://cloud.githubusercontent.com/assets/21422/13331534/efcf147a-dbcb-11e5-831f-7334e21a1aaf.PNG)
![img_1410](https://cloud.githubusercontent.com/assets/21422/13331535/efcf0ffc-dbcb-11e5-94ec-d9384896b28c.PNG)

**Comment by benpackard** [comment]
Thanks, I'll take a look. I think I get a full updated version of the
device in the call back after sending an action, so I'll try that first. I
was missing that the device's actions can change not only state, but might
be removed or supplemented after a chance.

This won't help with changes initiated from elsewhere though since in that
case I only get from ZettaKit the new value for the updated stream, and not
the full device state (as we discussed).

**Comment by mdobson** [comment]
Ben,

The streaming interface should include new actions for devices along with
their inputs. I've added this into the SDK drop that will happen sometime
tomorrow. This should solve the problem.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment]
@mdobson Can you give a little more info about how to get the new actions from the received `ZIKStreamEntry`? Does it similarly include the updated device properties (I need these for the new state icon)? 

When an `ZIKTransition` is fired, the callback returns a fully updated `ZIKDevice` - does the `ZIKStreamEntry` operate in the same way?

**Comment by landlessness** [comment]
fwiw, the `actions` are now updating when I fire the transition using the button in the app. but the `actions` are not updating in the iOS app when i fire the transition from, say, the Zetta browser. so the original intent of @anil614sagar's issue still stands. whereas my comment above has been addressed (by me remembering to call the callback :) ).

**Comment by mdobson** [comment]
Ben,

This was a gap in the SDK. In the latest drop (0.0.8) being pushed out as
we speak I've added a method on ZIKDevice that will allow you to provide a
log stream entry, and have a devices actions and properties updated. Method
signature below.

-(void)refreshWithLogEntry:(ZIKLogStreamEntry \* _Nonnull)entry;

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment]
Very cool, thanks. But it seems like the stream updates are arriving via the `ZIKStreamEntry`, not the `ZIKLogStreamEntry`. For example, from the photocell:

```
stream.signal.subscribeNext({ [weak self] (streamEntry) -> Void in
    print(streamEntry)
})
stream.resume()
```

```
<ZIKStreamEntry: photocell/df676540-f126-4c06-bb0b-8a80e7d34982/intensity = 0>
<ZIKStreamEntry: photocell/df676540-f126-4c06-bb0b-8a80e7d34982/intensity = 0.0340741737097473>
<ZIKStreamEntry: photocell/df676540-f126-4c06-bb0b-8a80e7d34982/intensity = 0.1339745962179103>
<ZIKStreamEntry: photocell/df676540-f126-4c06-bb0b-8a80e7d34982/intensity = 0.2928932188027525>
<ZIKStreamEntry: photocell/df676540-f126-4c06-bb0b-8a80e7d34982/intensity = 0.4999999999949269>
```

**Comment by mdobson** [comment]
That looks like a custom zetta stream for the intensity property. Actions
won't come from this stream. Only the _intensity_ value comes down this
stream. They will come down the *logs *stream every time a transition
happens. Is a method needed for updating the device for custom streams like
the intensity stream?

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment]
No I don't think so right now. I just fired up a Hue Bulb and I'm seeing a log stream come through to the app when I fire an action on the browser, so I think we're good. Going to try updating the device with these streams shortly.

**Comment by benpackard** [comment]
Working nicely, thanks @mdobson.
